image: node:12

stages:
  - style
  - compile
  - publish
  - unit-test
  - mock-api-test
  - full-test-suite
  # - deploy-lambdas

# Cache modules in between jobs
cache:
  paths:
    - node_modules

before_script:
  - node --version
  - npm --version
  - npm set strict-ssl false
  - npm config set registry https://registry.npmjs.org/
  - npm ci

build:
  stage: compile
  except:
    - master
  script:
    - npm run build
  retry: 2
  tags:
    - openshift
    - kubernetes

style:
  stage: style
  except:
    - master
  script:
    - npm run lint
    - npm run prettier:fix
  retry: 2
  tags:
    - openshift
    - kubernetes

pages: # the job must be named pages
  stage: publish
  script:
    - npm run publish
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master
  tags:
    - kubernetes
    - openshift

unit-test:
  stage: unit-test
  except:
    - master
  script:
    - npm run test:unit
  coverage: /^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/
  retry: 2
  tags:
    - openshift
    - kubernetes

mock-api-test:
  stage: mock-api-test
  except:
    - master
  script:
    - npm run test:mock
  coverage: /^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/
  retry: 2
  tags:
    - openshift
    - kubernetes

full-test-suite:
  stage: full-test-suite
  only:
    - master
  script:
    - npm run test:full
  coverage: /^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/
  retry: 2
  tags:
    - openshift
    - kubernetes

# UNCOMMENT TO DEPLOY TO AWS ENVIRONMENT
# deploy-lambdas-dev:
#   stage: deploy-lambdas
#   only:
#     - develop # can set certain AWS environments to deploy from different repo branches
#   script:
#     - SLS_DEBUG=* node_modules/serverless/bin/serverless deploy -v
#   variables:
#     AWS_ENV: dev # can have n different AWS environments to deploy to, as long as each has a {env-name}.yml file in the env directory
#   tags:
#     -  # tags for GitLab runner